name = "red-packet-dapp"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "red-packet-dapp"

[env.preview] 
name = "red-packet-dapp-preview"

# Pages 配置
pages_build_output_dir = "dist"

# 环境变量
[vars]
NODE_ENV = "production"

# 自定义域名（可选，替换为你的域名）
# [env.production.vars]
# CUSTOM_DOMAIN = "your-domain.com"

# 开发环境配置
[env.development]
name = "red-packet-dapp-dev"

[env.development.vars]
NODE_ENV = "development"
